booktime/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from .views import ContactUsView, ProductListView
from main import models

urlpatterns = [    
    path('', TemplateView.as_view(template_name="home.html"), name='home'),
    path('about/', TemplateView.as_view(template_name="about.html"), name='about'),
    path('contact/', ContactUsView.as_view(template_name="contact.html"), name='contact'),
    path('products/<slug:tag>/', ProductListView.as_view(), name='products'),
    path('product/<slug:slug>/', DetailView.as_view(model=models.Product,  template_name = 'product_detail.html'), name='products'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import(AbstractUser, BaseUserManager)

class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()




class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class ProductTagManager(models.Manager):
    def get_by_natural_key(self, slug):
        return self.get(slug = slug)

class ProductTag(models.Model):
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)
    objects = ProductTagManager()

    def __str__(self):
        return self.name

    def natural_key(self):
        return (self.slug)



class Product(models.Model):
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(ProductTag, blank=True)
    objects = ActiveManager()
    

    def __str__(self):
        return self.name

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")
    thumbnail = models.ImageField(upload_to="product-thumbnails", null=True)

main/forms.py
from django.core.mail import send_mail
import logging
from django import forms

logger = logging.getLogger(__name__)

class ContactForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    message = forms.CharField(max_length=600, widget=forms.Textarea)

    def send_mail(self):
        logger.info("Sending email to customer service")
        message = "From: {0}\n{1}".format(
            self.cleaned_data["name"],
            self.cleaned_data["message"]
        )
        send_mail("Site message",
        message,
        "site@booktime.domain",
        ["customerservice@booktime.domain"],
        fail_silently=False,
         )   

main/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from main import forms
from main import models
from .models import Product

class ContactUsView(FormView):
    template_name = 'contact.html'
    form_class = forms.ContactForm
    success_url = '/'

    def form_valid(self, form):
        form.send_mail()
        return super().form_valid(form)

class ProductDetailView(DetailView):
    template_name = 'product_detail.html'
    
    
class ProductListView(ListView):
    template_name = 'product_list.html'
    paginate_by = 4

    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None
        if tag != "all":
            self.tag = get_object_or_404(models.ProductTag, slug=tag)
        if self.tag:
            products = models.Product.objects.active().filter(tags = self.tag)
        else:
            products = models.Product.objects.active()
        return products.order_by("name")

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>About us</h2>
<p>BookTime is a company that sells books online.</p>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <title>BookTime</title>
    <meta charset="utf-8">
    <metaname="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet"href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>   
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">BookTime</a>
        <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div
        class="collapse navbar-collapse"
        id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li
        class="nav-item {% if request.path == '/' %}active{% endif %}">
        <a class="nav-link" href="/">Home</a>
        </li>
        <li
        class="nav-item {% if request.path == '/about/' %}active{% endif %}">
        <a class="nav-link" href="/about/">About us</a>
        </li>
        </ul>
        </div>
        </nav>
    {% block content %}
    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
<h2>Contact us</h2>
<p>Please fill the form below to contact us</p>
<form method="POST">
{% csrf_token %}
<!-- {{ form|crispy }} -->
<div class="form-group">
    {{ form.name.label_tag }}
    <input type="text" class="form-control {% if form.name.errors %}is-invalid{%endif %}" id="id_name" name="name" placeholder="Your name"
    value="{{ form.name.value|default:'' }}" >
    {% if form.name.errors %}
    <div class="invalid-feedback">
    {{ form.name.errors }}
    </div>
    {% endif %}
</div>
    
<div class="form-group">
    {{ form.message.label_tag }}
    <textarea
    class="form-control {% if form.message.errors %}is-invalid{%endif %}"
    id="id_message"
    name="message"
    rows="3">
    {{ form.message.value|default:""}}
    </textarea>
    {% if form.message.errors %}
    <div class="invalid-feedback">
         {{ form.message.errors }}
    </div>
    {% endif %}
</div>
<button type="submit" class="btn btn-primary">Submit
</button>
</form>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Home</h2>
<p>this will be the content of home</p>
{% endblock content %}

templates/product_detail.html
{% extends "base.html" %}
{% block content %}
<h1>products</h1>
<table class="table">
<tr>
<th>Name</th>
<td>{{ object.name }}</td>
</tr>
<tr>
<th>Cover images</th>
<td>
{% for image in object.productimage_set.all %}
<img src="{{ image.thumbnail.url }}" alt="cover"/>
{% endfor %}
</td>
</tr>
<tr>
<th>Price</th>
<td>{{ object.price }}</td>
</tr>
<tr>
<th>Description</th>
<td>{{ object.description|linebreaks }}</td>
</tr>
<tr>
<th>Tags</th>
<td>{{ object.tags.all|join:","}}</td>
</tr>
<tr>
    <th>In stock</th>
    <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
    <th>Updated</th>
    <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>
    </table>  
        <a href="#">Add to basket</a>
    {% endblock content %}

templates/product_list.html
{% extends "base.html" %}
{% block content %}
<h1>products</h1>
{% for product in page_obj %}
    <p>{{ product.name }}</p>
    <p>
    <a href="{% url 'products' product.slug %}">See it here</a>
    </p>
    {% if not forloop.last %}
    <hr>
    {% endif %}
{% endfor %}
<nav>
    <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a
            class="page-link"
            href="?page={{page_obj.previous_page_number}}">
            Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
            </li>
    {% endif %}
    {% for pagenum in page_obj.paginator.page_range %}
        <li
            class="page-item{% if page_obj.number == pagenum %}
            active{% endif %}">
            <a class="page-link" href="?page={{pagenum}}">{{pagenum}}
            </a>
        </li>
    {% endfor %}
    {% if page_obj.has_next %}
            <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_
            page_number}}">Next</a>
        </li>
    {% else %}
        <li class="page-item disabled">
             <a class="page-link" href="#">Next</a>
        </li>
    {% endif %}
    </ul>
</nav>
{% endblock content %}